# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'images/**'
      - 'docs/**'
      - 'examples/**'
      - 'packages/**'
      - 'README.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'images/**'
      - 'docs/**'
      - 'examples/**'
      - 'packages/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_DISABLE_GUI_ERRORS: 1
      DOTNET_GENERATE_ASPNET_CERTIFICATE: 0
      DOTNET_NOLOGO: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: |
          dotnet restore src\TBC.OpenAPI.SDK.Core\TBC.OpenAPI.SDK.Core.csproj
          dotnet restore tests\TBC.OpenAPI.SDK.Core.Tests\TBC.OpenAPI.SDK.Core.Tests.csproj

      - name: Build
        run: |
          dotnet build src\TBC.OpenAPI.SDK.Core\TBC.OpenAPI.SDK.Core.csproj \
            -c Release \
            --no-restore \
            -p:SourceRevisionId=$(git rev-parse --short $GITHUB_SHA)

      - name: Test
        run: |
          dotnet test tests\TBC.OpenAPI.SDK.Core.Tests\TBC.OpenAPI.SDK.Core.Tests.csproj \
            -c Release \
            --no-build \
            --no-restore \
            --verbosity normal
